version: "3"

volumes:
  mongo_data:
    driver: local
services:
  mongo:
    container_name: mern-sample-mongo
    restart: unless-stopped
    image: mongo
    ports:
      - "29017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME:"user"
      - MONGO_INITDB_ROOT_PASSWORD:"pass"
    volumes:
      - ./mongo_data:/data/mernsample_db